window.SPEC_PROJECTS = [
  {
    id: 'battery-doctor',
    archiveTitle: 'Battery Doctor',
    title: 'Battery Doctor',
    subtitle: 'STM32-based LiFePO4 battery diagnostics and cell-health monitoring.',
    status: 'R&D',
    year: '2026',
    categories: ['Embedded', 'Power / Battery', 'Instrumentation'],
    tags: ['STM32', 'LiFePO4', 'TFT', 'Cell Monitoring', 'Diagnostics'],
    overview: 'Battery Doctor is a low-cost battery diagnostic platform focused on per-cell voltage monitoring, imbalance detection, load-sag observation, recovery behavior, and clear on-device status display.',
    objective: 'Build a practical diagnostic tool that helps evaluate LiFePO4 cell behavior instead of showing only pack voltage.',
    architecture: ['Cell voltage sensing', 'STM32 acquisition and calibration', 'Diagnostic logic', 'TFT status and readings', 'Bench load / recovery testing'],
    hardware: ['STM32 controller', 'LiFePO4 battery cells', 'Voltage-divider sensing network', '2.8-inch TFT display', 'Load and wiring for controlled tests'],
    software: ['Embedded firmware for ADC acquisition', 'Per-channel calibration factors', 'Cell delta and low-cell checks', 'Display and diagnostic status logic'],
    testing: ['Stable per-cell voltage reading', 'Cell-to-cell delta observation', 'Load-sag comparison', 'Recovery after load removal', 'Calibration against reference measurements'],
    limitations: ['Prototype diagnostic platform, not a replacement for a certified BMS', 'Accuracy depends on resistor tolerance, ADC behavior, calibration, and wiring', 'Higher-series-count versions require safer and more advanced front-end design'],
    future: ['Expand to higher cell counts', 'Add logging and historical trend analysis', 'Improve isolation / front-end protection', 'Add battery-health scoring from repeated test data']
  },
  {
    id: 'smartlink',
    archiveTitle: 'SmartLink Wireless Telemetry',
    title: 'SmartLink Wireless Telemetry',
    subtitle: 'STM32 + nRF24L01 link-health and packet-reliability research.',
    status: 'R&D',
    year: '2026',
    categories: ['Embedded', 'Wireless', 'Instrumentation'],
    tags: ['STM32', 'nRF24L01', 'Telemetry', 'Packet Loss', 'RF Testing'],
    overview: 'SmartLink is an STM32-to-STM32 wireless telemetry research platform that measures more than successful reception. It tracks missed packets, duplicates, timing behavior, jitter, timeout, and link-health conditions.',
    objective: 'Create a reusable low-cost telemetry link with measurable reliability and clearer failsafe behavior for robotics and embedded projects.',
    architecture: ['Transceiver A packet generation', 'nRF24L01 wireless link', 'Transceiver B validation', 'Packet counters and timing analysis', 'Health-state / timeout logic'],
    hardware: ['STM32F103-class boards', 'nRF24L01+ modules', '3.3 V power filtering / decoupling', 'Serial interface for diagnostics'],
    software: ['Packet IDs and validation', 'Missed / duplicate packet counters', 'Jitter and interval monitoring', 'Timeout and link-health logic'],
    testing: ['Stable bench packet runs', 'Diagnostic runs under unstable conditions', 'RF sensitivity tests near the module / antenna', 'Planned distance and interference validation'],
    limitations: ['Bench reliability does not equal certified field reliability', 'RF performance is sensitive to antenna placement, power quality, nearby objects, and interference'],
    future: ['Distance testing', 'Interference testing', 'Moving-platform validation', 'Dedicated PCB revision with improved RF layout and antenna clearance']
  },
  {
    id: 'ai-sack-counter',
    archiveTitle: 'AI Sack Counter + Modbus',
    title: 'AI Sack Counter + Modbus',
    subtitle: 'Raspberry Pi edge-vision proof of concept for industrial counting and PLC integration.',
    status: 'Industrial PoC',
    year: '2026',
    categories: ['AI / Vision', 'Industrial', 'Embedded'],
    tags: ['Raspberry Pi 5', 'Camera', 'OpenCV', 'YOLO', 'Modbus'],
    overview: 'This proof of concept uses a Raspberry Pi camera pipeline to detect and count sacks, then prepares the resulting count for industrial integration through Modbus.',
    objective: 'Demonstrate a low-cost AI vision node that can provide a machine-readable count to a PLC or industrial controller.',
    architecture: ['Camera video input', 'Raspberry Pi image processing', 'Object detection / counting logic', 'Count validation', 'Modbus register output for PLC integration'],
    hardware: ['Raspberry Pi 5', 'Camera system', 'Network / serial interface depending on Modbus implementation', 'Industrial PLC on the integration side'],
    software: ['OpenCV capture and frame handling', 'YOLO-style object detection workflow', 'Counting logic', 'Modbus communication layer'],
    testing: ['Camera frame-rate and exposure tests', 'Object-counting proof-of-concept tests', 'Count-to-Modbus integration planning'],
    limitations: ['Accuracy depends on camera position, lighting, occlusion, training data, and target flow', 'Industrial deployment requires enclosure, power, networking, validation, and fail-safe planning'],
    future: ['Train and validate on real sack datasets', 'Add count confidence and event logging', 'Harden Modbus communication', 'Build an industrial demo enclosure']
  },
  {
    id: 'lidar-autonomous-robot',
    archiveTitle: 'LiDAR Autonomous Robot',
    title: 'LiDAR Autonomous Robot',
    subtitle: 'Raspberry Pi + ESP32 mobile robot with LiDAR sensing and mission navigation.',
    status: 'Prototype',
    year: '2026',
    categories: ['Robotics', 'Embedded', 'Navigation'],
    tags: ['LiDAR', 'Raspberry Pi', 'ESP32', 'Motor Control', 'AprilTag'],
    overview: 'A mobile robotics platform using LiDAR obstacle sensing, Raspberry Pi mission processing, ESP32 motor control, and visual target markers for navigation experiments.',
    objective: 'Develop custom autonomous navigation logic without depending on a full ROS / SLAM stack for the core mission behavior.',
    architecture: ['LiDAR obstacle sectors', 'Raspberry Pi navigation logic', 'Visual target / AprilTag detection', 'Serial motor commands', 'ESP32 low-level motor control'],
    hardware: ['Raspberry Pi', 'ESP32', '2D LiDAR', 'Motor drivers and drive motors', 'Camera for visual tags'],
    software: ['Custom obstacle-sector logic', 'Target detection and centering', 'Serial motion command protocol', 'Motor speed / turn control'],
    testing: ['Front / side obstacle thresholds', 'Target centering and approach', 'Motor command timing', 'Obstacle avoidance behavior'],
    limitations: ['Prototype navigation logic is environment-specific', 'Performance depends on LiDAR mounting, calibration, traction, camera visibility, and obstacle geometry'],
    future: ['Improve mapping / localization', 'Add better path planning', 'Improve closed-loop motion control', 'Expand mission-state handling']
  },
  {
    id: 'smart-mppt',
    archiveTitle: 'Smart MPPT Solar Controller',
    title: 'Smart MPPT Solar Controller',
    subtitle: 'Microcontroller-based solar charge-controller R&D with sensing, charging logic, and protection.',
    status: 'R&D',
    year: '2026',
    categories: ['Power / Solar', 'Embedded'],
    tags: ['STM32', 'MPPT', 'Solar', 'Power Electronics', 'Battery Charging'],
    overview: 'A low-cost MPPT solar controller research platform intended for DIY and off-grid applications, using microcontroller-based power tracking and battery charging logic.',
    objective: 'Build a controller that is more capable than simple PWM charging while remaining understandable, testable, and practical to prototype.',
    architecture: ['PV voltage/current sensing', 'DC-DC power stage', 'MPPT algorithm', 'Battery CC/CV/float logic', 'Protection and status monitoring'],
    hardware: ['STM32 / ESP32-class controller', 'MOSFET gate driver and switching MOSFETs', 'Inductor and output capacitors', 'Current and voltage sensors', 'Protection components'],
    software: ['Perturb-and-observe MPPT direction', 'Planned incremental / adaptive MPPT', 'Battery charging state logic', 'Fault and limit checks'],
    testing: ['Sensor calibration', 'PV operating-point tracking', 'Charge-stage behavior', 'Thermal and switching observation'],
    limitations: ['Power-electronics prototypes require careful thermal, EMI, over-current, and over-voltage design', 'Bench results must be validated across real PV and battery conditions'],
    future: ['Higher-efficiency power stage', 'Improved MPPT algorithm', 'Data logging / display', 'Commercial-prototype protection and PCB design']
  },
  {
    id: 'engineering-test-instruments',
    archiveTitle: 'Engineering Test Instruments',
    title: 'Engineering Test Instruments',
    subtitle: 'Low-cost embedded measurement and visualization tools for prototype development.',
    status: 'Prototype',
    year: '2026',
    categories: ['Instrumentation', 'Embedded'],
    tags: ['ESP32', 'STM32', 'Python', 'Oscilloscope', 'Logic Analyzer', 'DAQ'],
    overview: 'A group of low-cost embedded test-tool experiments covering waveform capture, digital logic observation, signal generation, current / voltage analysis, and PC-side visualization.',
    objective: 'Create accessible diagnostic tools for development and education while understanding the limits of MCU-based instrumentation.',
    architecture: ['Sensor / signal inputs', 'MCU acquisition', 'High-speed serial transfer', 'Python or local display visualization', 'Measurement / analysis functions'],
    hardware: ['ESP32 and STM32 boards', 'ADS1115 ADC modules', 'Current sensors', 'Voltage-divider inputs', 'TFT / LCD displays'],
    software: ['ADC sampling firmware', 'Logic capture and timing analysis', 'Serial data protocol', 'Python visualization / GUI experiments'],
    testing: ['Sampling-rate checks', 'Input scaling and divider validation', 'Frequency / PWM measurement', 'Noise and serial-throughput observation'],
    limitations: ['Not a substitute for calibrated laboratory oscilloscopes or certified analyzers', 'Bandwidth, ADC resolution, timing accuracy, and input protection are MCU-limited'],
    future: ['Better trigger logic', 'Improved input protection', 'Calibration workflow', 'Unified desktop interface']
  },
  {
    id: 'water-quality',
    archiveTitle: 'Water Quality Monitoring',
    title: 'Water Quality Monitoring',
    subtitle: 'ESP32 sensor-monitoring architecture for water condition, level, and dashboard reporting.',
    status: 'Prototype Direction',
    year: '2026',
    categories: ['Instrumentation', 'Embedded', 'IoT'],
    tags: ['ESP32', 'pH', 'Temperature', 'Water Level', 'Dashboard'],
    overview: 'A water-monitoring project direction combining pH, water temperature, level sensing, alerts, and dashboard reporting.',
    objective: 'Provide a practical multi-sensor monitoring platform that can be expanded toward hydroponics, tank monitoring, or environmental observation.',
    architecture: ['pH sensing', 'Water temperature sensing', 'Level sensing', 'ESP32 processing', 'Local / remote dashboard and alerts'],
    hardware: ['ESP32', 'pH sensor interface', 'DS18B20-class temperature sensor', 'Water-level / distance sensor', 'Optional display / communication module'],
    software: ['Sensor acquisition', 'Calibration and threshold logic', 'Dashboard reporting', 'Alert conditions'],
    testing: ['Sensor calibration', 'Cross-check against reference readings', 'Longer-duration stability tests'],
    limitations: ['pH sensors require regular calibration and proper probe maintenance', 'Prototype readings should not be treated as certified laboratory measurements'],
    future: ['Data logging', 'Automatic dosing research', 'Additional EC / TDS / NPK sensors', 'Improved enclosure and probe handling']
  },
  {
    id: 'gps-tracking',
    archiveTitle: 'GPS Tracking & Monitoring',
    title: 'GPS Tracking & Monitoring',
    subtitle: 'Embedded tracking architecture using GPS with wireless reporting and geofencing.',
    status: 'Prototype Direction',
    year: '2026',
    categories: ['Embedded', 'IoT', 'Tracking'],
    tags: ['GPS', 'GSM', 'LoRa', 'Wi-Fi', 'Geofencing'],
    overview: 'A flexible GPS tracking architecture for position, movement history, geofencing, and remote reporting using cellular, LoRa, or Wi-Fi communication.',
    objective: 'Provide a reusable tracking platform that can be adapted to vehicles, robots, equipment, or field assets.',
    architecture: ['GPS position acquisition', 'MCU data processing', 'Wireless communication', 'Remote dashboard / map', 'Geofence and movement-history logic'],
    hardware: ['GPS module', 'ESP32 / MCU', 'Optional GSM / LoRa module', 'Power supply and antenna system'],
    software: ['NMEA / GPS parsing', 'Coordinate filtering', 'Communication layer', 'Geofence and logging logic'],
    testing: ['Satellite lock and update rate', 'Communication reliability', 'Location repeatability', 'Power consumption'],
    limitations: ['GPS accuracy depends on sky view and receiver quality', 'Communication coverage depends on the selected network'],
    future: ['Offline buffering', 'Better map dashboard', 'Power-saving modes', 'Multi-device fleet view']
  },
  {
    id: 'omni-mecanum-parts',
    archiveTitle: 'Omni / Mecanum Robot Parts',
    title: 'Omni / Mecanum Robot Parts',
    subtitle: '3D-printed drivetrain and wheel-development experiments for mobile robotics.',
    status: 'Mechanical R&D',
    year: '2026',
    categories: ['Fabrication', 'Robotics'],
    tags: ['3D Printing', 'TPU', 'PETG', 'Omni Wheel', 'Mecanum'],
    overview: 'Mechanical prototyping work focused on custom omni / mecanum-style wheel parts, roller geometry, fit, vibration, and manufacturability using 3D-printed materials.',
    objective: 'Develop practical robot drivetrain parts that can be iterated quickly using in-house fabrication.',
    architecture: ['Wheel-body CAD', 'Roller geometry', 'Material selection', '3D printing', 'Fit / motion testing'],
    hardware: ['3D printers', 'TPU rollers', 'PETG / rigid wheel frames', 'Bearings / shafts / fasteners'],
    software: ['FreeCAD / CAD workflow', 'Slicer configuration', 'Iterative dimensional adjustment'],
    testing: ['Roller contact behavior', 'Vibration and runout', 'Fit and clearance', 'Wheel diameter / roller protrusion checks'],
    limitations: ['Printed wheel performance depends heavily on geometry, print accuracy, material hardness, and bearing alignment'],
    future: ['Refine roller angle / spacing', 'Improve bearing support', 'Compare omni vs mecanum configurations', 'Create stronger production-ready CAD']
  },
  {
    id: 'pcb-fabrication',
    archiveTitle: 'PCB Fabrication Experiments',
    title: 'PCB Fabrication Experiments',
    subtitle: 'In-house PCB prototyping using KiCad, dry film, UV exposure, developing, and etching.',
    status: 'Workshop R&D',
    year: '2026',
    categories: ['Fabrication', 'Embedded'],
    tags: ['KiCad', 'PCB', 'Dry Film', 'UV Exposure', 'Etching'],
    overview: 'Workshop research into producing small prototype PCBs in-house using dry-film photoresist and iterative exposure / developing / etching methods.',
    objective: 'Reduce turnaround time for simple prototype boards and improve understanding of manufacturable PCB layout.',
    architecture: ['KiCad PCB layout', 'Artwork / mask preparation', 'Dry-film lamination', 'UV exposure', 'Developing', 'Copper etching', 'Inspection / drilling'],
    hardware: ['UV exposure source', 'Copper-clad board', 'Dry-film photoresist', 'Developer / etching setup', 'Workshop cutting and drilling tools'],
    software: ['KiCad schematic and PCB layout', 'Print / artwork preparation'],
    testing: ['Exposure-time trials', 'Developer concentration / timing', 'Trace adhesion and resolution inspection'],
    limitations: ['Home fabrication has tighter limits on fine-pitch routing, plated vias, solder mask, and repeatability', 'Chemical handling and disposal require proper safety practice'],
    future: ['Improve trace resolution', 'Standardize exposure and development process', 'Add drilling / alignment fixtures', 'Move complex boards to professional fabrication']
  },
  {
    id: 'e-kulambo',
    archiveTitle: 'E-KULAMBO Dengue Environmental Risk Warning System',
    title: 'E-KULAMBO Dengue Environmental Risk Warning System',
    subtitle: 'ESP32 multi-parameter environmental monitoring with fuzzy-logic risk classification.',
    status: 'Academic Prototype',
    year: '2026',
    categories: ['Embedded', 'Instrumentation', 'IoT'],
    tags: ['ESP32', 'DHT22', 'Rain / Wet', 'Turbidity', 'Fuzzy Logic', 'Dashboard'],
    overview: 'E-KULAMBO is an environmental dengue-risk warning prototype that combines temperature, humidity, wet / rain conditions, and turbidity-related sensing with fuzzy-logic classification.',
    objective: 'Estimate environmental conditions that may favor mosquito breeding and present an easy-to-understand risk status for monitoring.',
    architecture: ['Environmental sensors', 'ESP32 acquisition', 'Sensor normalization / status logic', 'Fuzzy-logic risk classification', 'LCD / LEDs / buzzer', 'Local dashboard'],
    hardware: ['ESP32', 'DHT22', 'Rain / wet sensor', 'Turbidity sensor', 'I2C LCD', 'Status LEDs and buzzer'],
    software: ['Sensor validation', 'Fuzzy membership / rule evaluation', 'Normal / Moderate / Critical style status output', 'Dashboard reporting'],
    testing: ['Air vs water turbidity-sensor response', 'Wet / rain-state checks', 'Temperature and humidity acquisition', 'Fault-tolerant display / dashboard behavior'],
    limitations: ['The system does not directly detect dengue virus', 'It does not count mosquitoes', 'Environmental risk classification depends on sensor quality and the selected fuzzy rules'],
    future: ['Improve turbidity calibration', 'Collect longer environmental datasets', 'Validate rule thresholds with domain references', 'Improve enclosure and field deployment']
  },
  {
    id: 'chicken-stress',
    archiveTitle: 'Chicken Stress Detection & Monitoring',
    title: 'Chicken Stress Detection & Monitoring',
    subtitle: 'Raspberry Pi audio classification with temperature / humidity context and Firebase monitoring.',
    status: 'Academic Prototype',
    year: '2026',
    categories: ['AI / Vision', 'Instrumentation', 'Embedded'],
    tags: ['Raspberry Pi', 'Audio Classification', 'Microphone', 'DHT', 'Firebase'],
    overview: 'A poultry-monitoring prototype that analyzes short microphone recordings to classify chicken vocalization patterns while using temperature and humidity data as additional context for possible heat stress.',
    objective: 'Provide a non-invasive prototype for observing poultry stress indicators using audio patterns and environmental measurements.',
    architecture: ['Microphone audio capture', 'Short audio-window preprocessing', 'Feature extraction / classifier', 'NORMAL / STRESS / OTHER output', 'Temperature / humidity context', 'Firebase logging / monitoring'],
    hardware: ['Raspberry Pi', 'Microphone', 'Temperature / humidity sensor', 'Network connection for Firebase'],
    software: ['Python audio capture', 'Audio preprocessing and feature extraction', 'Classifier logic', 'Environmental condition checks', 'Firebase reporting'],
    testing: ['Audio-window capture consistency', 'Class-output observation', 'Temperature / humidity reading checks', 'Remote status logging'],
    limitations: ['Stress cannot be medically or biologically confirmed from vocalization alone', 'Classification quality depends on the training / reference audio and environmental noise', 'Heat-stress context should be treated as a screening indicator'],
    future: ['Collect and label a larger poultry-audio dataset', 'Improve noise rejection', 'Validate classification against expert observations', 'Add trend and event-history visualization']
  },
  {
    id: 'garbage-robot',
    archiveTitle: 'Autonomous Garbage Collection Robot',
    title: 'Autonomous Garbage Collection Robot',
    subtitle: 'LiDAR-guided mobile robot with AprilTag alignment and linear-actuator waste handling.',
    status: 'Robotics Prototype',
    year: '2026',
    categories: ['Robotics', 'Embedded', 'Fabrication'],
    tags: ['Raspberry Pi', 'LiDAR', 'AprilTag', 'Linear Actuator', 'Gyro', 'Motor Control'],
    overview: 'A mobile waste-handling robot prototype that combines autonomous navigation, target alignment, obstacle sensing, and a mechanical collection / dumping mechanism.',
    objective: 'Demonstrate a robot that can navigate toward a defined target, avoid obstacles, align itself, and actuate a garbage-handling mechanism.',
    architecture: ['LiDAR obstacle sensing', 'Raspberry Pi mission-state logic', 'AprilTag target detection and centering', 'Gyro-assisted orientation', 'Motor-control interface', 'Linear-actuator collection / dumping mechanism'],
    hardware: ['Raspberry Pi', '2D LiDAR', 'Camera', 'Gyro / IMU', 'Drive motors and motor controller', 'Linear actuator / mechanical dumping assembly'],
    software: ['Mission states such as search, center, approach, avoid, align, dock, and return', 'Obstacle-sector logic', 'AprilTag pose / centering logic', 'Motor command interface', 'Actuator control routines'],
    testing: ['Obstacle threshold tests', 'Tag centering and approach', 'Mission-state transitions', 'Orientation / return behavior', 'Mechanical actuator operation'],
    limitations: ['Exact LiDAR model is intentionally left unspecified until hardware records are reconfirmed', 'Performance depends on traction, actuator load, target visibility, obstacle geometry, and calibration'],
    future: ['Improve closed-loop drive control', 'Add stronger localization', 'Refine mechanical collection mechanism', 'Add safer actuator current / limit protection']
  }
];
